language: node_js
node_js:
  - 8
before_install:
  - cd ./firebase-otp-services/
  - cd ./functions/
install: 
  - npm install -g firebase-tools
  - npm install
script:
  - firebase functions:config:set admin.type=$type
  - firebase functions:config:set admin.project_id=$project_id
  - firebase functions:config:set admin.private_key_id=$private_key_id
  - firebase functions:config:set admin.private_key=$private_key
  - firebase functions:config:set admin.client_email=$client_email
  - firebase functions:config:set admin.client_id=$client_id
  - firebase functions:config:set admin.auth_uri=$auth_uri
  - firebase functions:config:set admin.token_uri=$token_uri
  - firebase functions:config:set admin.auth_provider_x509_cert_url=$auth_provider_x509_cert_url
  - firebase functions:config:set admin.client_x509_cert_url=$client_x509_cert_url
  - npm run-script deploy
after_success:
after_failure:
branches:
  only:
  - master